### ISSUE TITLE
[LAB-650] **tool not found** error when running custom tools

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#688]
When running a basic pre-configured tool on a remote server, such as this example below:

```
from plex import CoreTools, plex_init
from plex import plex_run
from plex import plex_mint
import os

os.environ["RECIPIENT_WALLET"] = "0xA5B68dbA49cE48d0c1e0f29EA45885b5f83A0BD4"

fasta_local_filepaths = ["data/1_interim/target_sequence/af_reference_sequence.fasta"]

initial_io_cid = plex_init(
    CoreTools.COLABFOLD_MINI.value,
    sequence=fasta_local_filepaths
)

# run plex
completed_io_cid, completed_io_filepath = plex_run(initial_io_cid)

# print results
print("DAG filepath", completed_io_filepath)
print("DAG location", completed_io_cid)

# using the autotask webhook enables gasless minting
os.environ["AUTOTASK_WEBHOOK"] = "https://api.defender.openzeppelin.com/autotasks/e15b3f39-28f8-4d30-9bf3-5d569bdf2e78/runs/webhook/8315d17c-c493-4d04-a257-79209f95bb64/2gmqi9SRRAQMoy1SRdktai"
plex_mint(completed_io_cid)
```

I receive the expected output

```
ubuntu@ip-172-31-47-185:$ python src/leahlabs/basic.py 
plex init -t QmcRH74qfqDBJFku3mEDGxkAf6CSpaHTpdbe1pMkHnbcZD -i {"sequence": ["/home/ubuntu/leahlabs/data/1_interim/target_sequence/af_reference_sequence.fasta"]} --scatteringMethod=dotProduct --autoRun=false
The version of plex you are running (v0.10.3) is outdated.
We highly recommend running `plex upgrade`
Pinned IO JSON CID: QmeXwojbB4KmUwRwnrkT1T6Jrzp71nPTL4jxqRRRporyk4
The version of plex you are running (v0.10.3) is outdated.
We highly recommend running `plex upgrade`
Created working directory:  /home/ubuntu/jobs/d3d3a93f-2c05-4dbd-8126-313918cfa825
Initialized IO file at:  /home/ubuntu/jobs/d3d3a93f-2c05-4dbd-8126-313918cfa825/io.json
Processing IO Entries
Starting to process IO entry 0 
Job running...
Bacalhau job id: 05410e0b-8589-4ac2-8a2b-f2652e7048a2 

Computing default go-libp2p Resource Manager limits based on:
    - 'Swarm.ResourceMgr.MaxMemory': "8.4 GB"
    - 'Swarm.ResourceMgr.MaxFileDescriptors': 524288

Applying any user-supplied overrides on top.
Run 'ipfs swarm limit all' to see the resulting limits.

Success processing IO entry 0 
Finished processing, results written to /home/ubuntu/jobs/d3d3a93f-2c05-4dbd-8126-313918cfa825/io.json
Completed IO JSON CID: QmbMbRnUPDraUezJNur7YmLArapXBdVsASbbNZhFaJrKGY
2023/10/03 11:16:59 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
DAG filepath /home/ubuntu/jobs/d3d3a93f-2c05-4dbd-8126-313918cfa825/io.json
DAG location QmbMbRnUPDraUezJNur7YmLArapXBdVsASbbNZhFaJrKGY
The version of plex you are running (v0.10.3) is outdated.
We highly recommend running `plex upgrade`
Preparing NFT metadata...
Uploading NFT metadata to IPFS...
NFT metadata uploaded to IPFS: ipfs://QmU6bJG8VGn1zAmnhuabQxsU15Gur56VXu781UYVyKmJNf
Triggering minting process via Defender Autotask...
🌱🌱🌱🌱🌱
Minting process successful.
Thank you for making science more reproducible, open, and collaborative!
You can view your ProofOfScience NFT at https://testnets.opensea.io/account.
🌱🌱🌱🌱🌱
```

When running a script which uses a custom json tool manifest, however, such as this one:

```
from plex import CoreTools, plex_init
from plex import plex_run
from plex import plex_mint
import os

os.environ["RECIPIENT_WALLET"] = "0xA5B68dbA49cE48d0c1e0f29EA45885b5f83A0BD4"

tool_filepath = "tools/colabdesign/colabdesign.json"
pdb_path = "data/1_interim/target_conformation/6VJA_chain_D_extracted.pdb"
config_path = "tools/colabdesign/colabdesign.yaml"


initial_io_cid = plex_init(
    tool_path = tool_filepath,
    config = [config_path],
    protein = [pdb_path]
)

# run plex
completed_io_cid, completed_io_filepath = plex_run(initial_io_cid)

# print results
print("DAG filepath", completed_io_filepath)
print("DAG location", completed_io_cid)

# using the autotask webhook enables gasless minting
os.environ["AUTOTASK_WEBHOOK"] = "https://api.defender.openzeppelin.com/autotasks/e15b3f39-28f8-4d30-9bf3-5d569bdf2e78/runs/webhook/8315d17c-c493-4d04-a257-79209f95bb64/2gmqi9SRRAQMoy1SRdktai"
plex_mint(completed_io_cid)
```

I receive a **tool not found** error

```
ubuntu@ip-172-31-47-185: $ python src/leahlabs/advanced.py 
plex init -t tools/colabdesign/colabdesign.json -i {"config": ["/home/ubuntu/leahlabs/tools/colabdesign/colabdesign.yaml"], "protein": ["/home/ubuntu/leahlabs/data/1_interim/target_conformation/6VJA_chain_D_extracted.pdb"]} --scatteringMethod=dotProduct --autoRun=false
The version of plex you are running (v0.10.3) is outdated.
We highly recommend running `plex upgrade`
2023/10/03 11:19:25 tool not found
Traceback (most recent call last):
  File "src/leahlabs/advanced.py", line 13, in <module>
    initial_io_cid = plex_init(
  File "/home/ubuntu/.local/share/virtualenvs/leahlabs-rMPYC1e7/lib/python3.8/site-packages/plex/__init__.py", line 73, in plex_init
    raise PlexError("Failed to initialize IO JSON CID")
plex.PlexError: Failed to initialize IO JSON CID
If this error persists, please submit an issue at https://github.com/labdao/plex/issues
```

I could not identify the issue right away in the repo.

<sub>From [SyncLinear.com](https://synclinear.com) | [LAB-648](https://linear.app/convexitylabs/issue/LAB-648/tool-not-found-error-when-running-custom-json-manifests)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [LAB-649](https://linear.app/convexitylabs/issue/LAB-649/[lab-648]-tool-not-found-error-when-running-custom-json-manifests)</sub>

<sub>[LAB-650](https://linear.app/convexitylabs/issue/LAB-650/tool-not-found-error-when-running-custom-tools)</sub>

**Comment by NiklasTR** [comment]
My intuition is that the client does not automatically convert tool paths to absolute paths, while doing exactly this for file inputs. This causes an error on the golang level.

**Comment by thetechnocrat-dev** [comment]
stale
